"""Add preferences field to User model

Revision ID: 404181c54e4a
Revises: abda64a36258
Create Date: 2026-01-08 16:14:17.383300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '404181c54e4a'
down_revision = 'abda64a36258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferences', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferences')

    # ### end Alembic commands ###
