"""Initial database schema with 17 tables

Revision ID: abda64a36258
Revises: 
Create Date: 2026-01-08 13:18:14.519594

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'abda64a36258'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_tenants', sa.Integer(), nullable=True),
    sa.Column('active_tenants', sa.Integer(), nullable=True),
    sa.Column('trial_tenants', sa.Integer(), nullable=True),
    sa.Column('canceled_tenants', sa.Integer(), nullable=True),
    sa.Column('total_trainers', sa.Integer(), nullable=True),
    sa.Column('total_athletes', sa.Integer(), nullable=True),
    sa.Column('mrr', sa.Integer(), nullable=True),
    sa.Column('arr', sa.Integer(), nullable=True),
    sa.Column('workouts_created_today', sa.Integer(), nullable=True),
    sa.Column('check_ins_today', sa.Integer(), nullable=True),
    sa.Column('messages_sent_today', sa.Integer(), nullable=True),
    sa.Column('total_storage_used_gb', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('global_analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_global_analytics_date'), ['date'], unique=True)

    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subdomain', sa.String(length=50), nullable=False),
    sa.Column('subscription_tier', sa.String(length=20), nullable=True),
    sa.Column('subscription_status', sa.String(length=20), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('max_athletes', sa.Integer(), nullable=True),
    sa.Column('max_storage_gb', sa.Integer(), nullable=True),
    sa.Column('business_email', sa.String(length=120), nullable=True),
    sa.Column('business_phone', sa.String(length=20), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('custom_domain', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_subdomain'), ['subdomain'], unique=True)

    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('equipment', sa.String(length=50), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('tips', sa.Text(), nullable=True),
    sa.Column('primary_muscles', sa.JSON(), nullable=True),
    sa.Column('secondary_muscles', sa.JSON(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('qr_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercises_qr_code'), ['qr_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_exercises_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_price_id', sa.String(length=100), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('billing_cycle', sa.String(length=20), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('trial_start', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('athletes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trainer_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.String(length=50), nullable=True),
    sa.Column('experience_level', sa.String(length=20), nullable=True),
    sa.Column('training_frequency', sa.Integer(), nullable=True),
    sa.Column('current_weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('target_weight', sa.Float(), nullable=True),
    sa.Column('injuries', sa.Text(), nullable=True),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('trainer_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_athletes_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_athletes_trainer_id'), ['trainer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_athletes_user_id'), ['user_id'], unique=True)

    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('qr_code', sa.String(length=100), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=True),
    sa.Column('gym_location', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machines_qr_code'), ['qr_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_machines_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachment_url', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.Integer(), nullable=True),
    sa.Column('file_metadata', sa.JSON(), nullable=True),
    sa.Column('storage_type', sa.String(length=20), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('body_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('measurement_date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('body_fat', sa.Float(), nullable=True),
    sa.Column('muscle_mass', sa.Float(), nullable=True),
    sa.Column('chest', sa.Float(), nullable=True),
    sa.Column('waist', sa.Float(), nullable=True),
    sa.Column('hips', sa.Float(), nullable=True),
    sa.Column('arms', sa.Float(), nullable=True),
    sa.Column('thighs', sa.Float(), nullable=True),
    sa.Column('calves', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('body_measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_body_measurements_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_measurements_measurement_date'), ['measurement_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_body_measurements_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('check_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('body_fat_percentage', sa.Float(), nullable=True),
    sa.Column('chest', sa.Float(), nullable=True),
    sa.Column('waist', sa.Float(), nullable=True),
    sa.Column('hips', sa.Float(), nullable=True),
    sa.Column('thigh_left', sa.Float(), nullable=True),
    sa.Column('thigh_right', sa.Float(), nullable=True),
    sa.Column('arm_left', sa.Float(), nullable=True),
    sa.Column('arm_right', sa.Float(), nullable=True),
    sa.Column('photo_front_url', sa.String(length=255), nullable=True),
    sa.Column('photo_side_url', sa.String(length=255), nullable=True),
    sa.Column('photo_back_url', sa.String(length=255), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('hunger_level', sa.Integer(), nullable=True),
    sa.Column('motivation', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('trainer_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('check_ins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_check_ins_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_check_ins_check_in_date'), ['check_in_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_check_ins_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('fitness_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('goal_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fitness_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fitness_goals_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fitness_goals_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('meal_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('protein_g', sa.Integer(), nullable=True),
    sa.Column('carbs_g', sa.Integer(), nullable=True),
    sa.Column('fats_g', sa.Integer(), nullable=True),
    sa.Column('meal_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_plans_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_plans_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('personal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('date_achieved', sa.Date(), nullable=False),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personal_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personal_records_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_personal_records_date_achieved'), ['date_achieved'], unique=False)
        batch_op.create_index(batch_op.f('ix_personal_records_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_personal_records_machine_id'), ['machine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_personal_records_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workouts_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workouts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('food_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('meal_plan_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('calories_consumed', sa.Integer(), nullable=True),
    sa.Column('protein_consumed', sa.Integer(), nullable=True),
    sa.Column('carbs_consumed', sa.Integer(), nullable=True),
    sa.Column('fats_consumed', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('food_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_food_logs_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_logs_meal_plan_id'), ['meal_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_food_logs_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('workout_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('block_name', sa.String(length=50), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps_min', sa.Integer(), nullable=True),
    sa.Column('reps_max', sa.Integer(), nullable=True),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('rpe_target', sa.Float(), nullable=True),
    sa.Column('tempo', sa.String(length=20), nullable=True),
    sa.Column('weight_percentage', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_superset', sa.Boolean(), nullable=True),
    sa.Column('superset_group', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_exercises_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workout_exercises_workout_id'), ['workout_id'], unique=False)

    op.create_table('progress_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('workout_exercise_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sets_completed', sa.Integer(), nullable=True),
    sa.Column('reps_completed', sa.JSON(), nullable=True),
    sa.Column('weight_used', sa.Float(), nullable=True),
    sa.Column('rpe_actual', sa.Float(), nullable=True),
    sa.Column('difficulty_rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('form_check_video_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['workout_exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('progress_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_logs_athlete_id'), ['athlete_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_logs_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_logs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_logs_workout_exercise_id'), ['workout_exercise_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_logs_workout_exercise_id'))
        batch_op.drop_index(batch_op.f('ix_progress_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_progress_logs_date'))
        batch_op.drop_index(batch_op.f('ix_progress_logs_athlete_id'))

    op.drop_table('progress_logs')
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_exercises_workout_id'))
        batch_op.drop_index(batch_op.f('ix_workout_exercises_exercise_id'))

    op.drop_table('workout_exercises')
    with op.batch_alter_table('food_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_food_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_food_logs_meal_plan_id'))
        batch_op.drop_index(batch_op.f('ix_food_logs_date'))

    op.drop_table('food_logs')
    with op.batch_alter_table('workouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workouts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_workouts_athlete_id'))

    op.drop_table('workouts')
    with op.batch_alter_table('personal_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personal_records_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_personal_records_machine_id'))
        batch_op.drop_index(batch_op.f('ix_personal_records_exercise_id'))
        batch_op.drop_index(batch_op.f('ix_personal_records_date_achieved'))
        batch_op.drop_index(batch_op.f('ix_personal_records_athlete_id'))

    op.drop_table('personal_records')
    with op.batch_alter_table('meal_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_plans_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_meal_plans_athlete_id'))

    op.drop_table('meal_plans')
    with op.batch_alter_table('fitness_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fitness_goals_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_fitness_goals_athlete_id'))

    op.drop_table('fitness_goals')
    with op.batch_alter_table('check_ins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_check_ins_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_check_ins_check_in_date'))
        batch_op.drop_index(batch_op.f('ix_check_ins_athlete_id'))

    op.drop_table('check_ins')
    with op.batch_alter_table('body_measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_body_measurements_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_body_measurements_measurement_date'))
        batch_op.drop_index(batch_op.f('ix_body_measurements_athlete_id'))

    op.drop_table('body_measurements')
    op.drop_table('uploaded_files')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_receiver_id'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))

    op.drop_table('messages')
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machines_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_machines_qr_code'))

    op.drop_table('machines')
    with op.batch_alter_table('athletes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_athletes_user_id'))
        batch_op.drop_index(batch_op.f('ix_athletes_trainer_id'))
        batch_op.drop_index(batch_op.f('ix_athletes_tenant_id'))

    op.drop_table('athletes')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_tenant_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercises_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_exercises_qr_code'))

    op.drop_table('exercises')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_subdomain'))

    op.drop_table('tenants')
    with op.batch_alter_table('global_analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_global_analytics_date'))

    op.drop_table('global_analytics')
    # ### end Alembic commands ###
